import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('iyBEABCwk0Fl3Fh3CiEGjYGQImwJwQ0TwRyJnfAwaUACFFJjFPgoArVg7hNVp1dwVoAwSTDiJJdHAOfJgmO3VvF1jQgshADQBlUagjDwUzHYGgmIhKEVFifBBPBgtg_Hg0BdChKEhnHXHgoGlJFlfenSTl6TwVEBmtItmS07tG2f9RxVUIwgvM');
