import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('wYgAEAAAAEDMAGABgiBHPRglABIAAAABgnCBARCEDAIAAAAABeKCOBDAABCBFhJgghVEBAAJAAJAADBAg2JEBBBACADw9IAXhXOghAA4I-Ugx2JNENDAEACJDiQAAACCABAABAbB4N1QhD');
