import decodeRanges from '../../decode-ranges.mjs';

export default decodeRanges('wYIABAAAMBAgsghCAhkOBGBJTABAdchYKAitKg0UAH4PKRhxQlqRg_Bg1gnMhyEAiG4O8CDAaABAABAAJADAAAAFADAAAAAACABAABAAAAAAAAAABAABDAGADADAAAJAQECAEAQ');
